"""Research report on the combined Motley Fool dataset -> docs/fool_research.md (re-run after refreshing prices)."""
import io
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf

from collector.store import DATA_DIR
from fool.ingest import FOOL_DIR, PRICES_PATH

OUT = Path(__file__).resolve().parent.parent / "docs" / "fool_research.md"
SECTORS_PATH = FOOL_DIR / "sectors.parquet"
CAP_BINS = [0, 2e9, 10e9, 50e9, 200e9, np.inf]
CAP_LABELS = ["<2B", "2-10B", "10-50B", "50-200B", ">200B"]


def md(df: pd.DataFrame, index: bool = True, floatfmt: str = "{:.3f}") -> str:
    df = df.reset_index() if index else df
    fmt = lambda v: v.strftime("%Y-%m-%d") if isinstance(v, pd.Timestamp) else floatfmt.format(v) if isinstance(v, float) and not pd.isna(v) else ("" if pd.isna(v) else str(v))
    rows = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join(rows)


def pct(s: pd.Series) -> pd.Series:
    return (s * 100).round(1)


def sectors(symbols: list[str]) -> pd.Series:
    cache = pd.read_parquet(SECTORS_PATH) if SECTORS_PATH.exists() else pd.DataFrame(columns=["symbol", "sector"])
    known = dict(zip(cache["symbol"], cache["sector"]))
    uni = pd.read_parquet(DATA_DIR / "universe" / "universe.parquet").set_index("symbol")["sector"]
    for s in symbols:
        if known.get(s) is None:
            known[s] = uni.get(s) if s in uni.index and pd.notna(uni.get(s)) else (yf.Ticker(s).info.get("sector") if s in PRICE_SYMBOLS else None)
    pd.DataFrame({"symbol": list(known), "sector": list(known.values())}).to_parquet(SECTORS_PATH, index=False)
    return pd.Series(known)


def prerec_features(b: pd.DataFrame, series: dict) -> pd.DataFrame:
    spy = series["SPY"]["adj_close"]
    rows = []
    for r in b.itertuples():
        px = series.get(r.yf_symbol)
        if px is None or pd.isna(r.entry_date):
            rows.append({}); continue
        a = px["adj_close"]; t = r.entry_date; past = a[(a.index <= t) & (a.index > t - pd.Timedelta(days=365))]
        back = t - pd.Timedelta(days=365)
        if len(past) < 150 or a.index[0] > back:
            rows.append({}); continue
        rows.append({"mom_12m": past.iloc[-1] / past.iloc[0] - 1, "spy_12m": spy.asof(t) / spy.asof(back) - 1,
                     "from_52w_high": past.iloc[-1] / past.max() - 1, "from_52w_low": past.iloc[-1] / past.min() - 1})
    f = pd.DataFrame(rows, index=b.index)
    f["rel_mom_12m"] = f["mom_12m"] - f["spy_12m"]
    return f


def sell_review(d: pd.DataFrame, series: dict) -> pd.DataFrame:
    spy = series["SPY"]["adj_close"]; out = []
    buys = d[d.action == "BUY"]
    for s in d[d.action.isin(["SELL", "REDUCE"])].itertuples():
        px = series.get(s.yf_symbol)
        prior = buys[(buys.symbol == s.symbol) & (buys.rec_date < s.rec_date)]
        if px is None or prior.empty:
            continue
        a = px["adj_close"]; b = prior.iloc[0]
        if pd.isna(b.entry_adj) or a.index[-1] < s.rec_date:
            continue
        sell_px = a.asof(s.rec_date); after = s.rec_date + pd.Timedelta(days=365)
        row = {"symbol": s.symbol, "buy": b.rec_date, "sell": s.rec_date, "held_days": (s.rec_date - b.rec_date).days,
               "hold_ret": sell_px / b.entry_adj - 1, "hold_spy": spy.asof(s.rec_date) / spy.asof(b.entry_date) - 1}
        if a.index[-1] >= after:
            row["after_365d"] = a.asof(after) / sell_px - 1; row["after_spy"] = spy.asof(after) / spy.asof(s.rec_date) - 1
        out.append(row)
    r = pd.DataFrame(out)
    r["hold_excess"] = r["hold_ret"] - r["hold_spy"]; r["after_excess"] = r["after_365d"] - r["after_spy"]
    return r


def build() -> str:
    global PRICE_SYMBOLS
    d = pd.read_parquet(FOOL_DIR / "recs.parquet")
    prices = pd.read_parquet(PRICES_PATH)
    series = {s: g.set_index("date").sort_index() for s, g in prices.groupby("symbol")}
    PRICE_SYMBOLS = set(series)
    b = d[d.action == "BUY"].copy()
    b["cap_bucket"] = pd.cut(b["market_cap"], CAP_BINS, labels=CAP_LABELS)
    b["year"] = b["rec_date"].dt.year
    b = b.join(prerec_features(b, series))
    b["sector"] = b["symbol"].map(sectors(sorted(b["symbol"].unique())))
    labelled = b[b["ret_365d"].notna()]
    L: list[str] = []
    add = L.append

    add("# Motley Fool Stock Advisor: what the data says\n")
    add(f"Generated by `python -m fool.report` from `advisor/fool/recs.parquet` ({len(d)} rows) and `prices.parquet`. "
        "Nothing here is a trading signal; it describes what the picks looked like and how they did.\n")

    add("## 1. Headline findings\n")
    ex = labelled["excess_365d"]
    top = labelled["ret_365d"].nlargest(max(1, int(len(labelled) * 0.01)))
    trim = labelled["excess_365d"].drop(labelled["ret_365d"].nlargest(max(1, int(len(labelled) * 0.01))).index)
    add(f"- **Cadence is mechanical**: {b.groupby(b.rec_date.dt.to_period('M')).size().eq(2).mean():.0%} of months have exactly 2 BUYs, "
        f"{b.rec_date.dt.dayofweek.isin([3, 4]).mean():.0%} published Thursday/Friday, David and Tom alternate. "
        f"~{len(b) / b.rec_date.dt.year.nunique():.0f} BUYs a year over {b.rec_date.min():%Y-%m}..{b.rec_date.max():%Y-%m}.")
    add(f"- **{b.symbol.nunique()} distinct companies**, {int(b.is_repeat.sum())} repeat BUYs; median market cap at rec "
        f"${b.market_cap.median() / 1e9:.1f}B (mid/large cap, not micro-cap).")
    add(f"- **Typical pick is mediocre, the average is carried by a few giants.** 365-day median return {labelled.ret_365d.median():.1%}, "
        f"mean {labelled.ret_365d.mean():.1%}; only {(ex > 0).mean():.0%} of picks beat SPY over 365d (median excess {ex.median():+.1%}). "
        f"Dropping the top 1% of picks moves mean 365d excess from {ex.mean():+.1%} to {trim.mean():+.1%}.")
    add(f"- **Survivorship**: {b.ret_365d.isna().sum()} of {len(b)} BUYs still have no recomputed 365d return "
        "(horizon not elapsed or no price history); results above describe the labelled subset only.\n")

    add("## 2. Files and schema (`info()`)\n")
    add("| dataset | rows | notes |\n|---|---|---|")
    for name, note in [("newrecs", "2014-2025, all actions, from Fool's PDF"), ("picks_returns", "2002-2020 BUYs + Fool's own returns"),
                       ("recs", "merged, ML table"), ("prices", "daily close/adj_close for picked symbols + SPY")]:
        p = PRICES_PATH if name == "prices" else FOOL_DIR / f"{name}.parquet"
        add(f"| `{name}.parquet` | {len(pd.read_parquet(p))} | {note} |")
    buf = io.StringIO(); d.info(buf=buf)
    add("\n`recs.parquet`:\n\n```\n" + buf.getvalue() + "```\n")

    add("## 3. Numeric summary (`describe()`)\n")
    num = d.assign(market_cap=d["market_cap"] / 1e9).rename(columns={"market_cap": "market_cap_$B"}).select_dtypes("number").drop(columns=["buy_number"]).describe().T[["count", "mean", "std", "min", "50%", "max"]]
    add(md(num.round(3)) + "\n")

    add("## 4. Coverage over time\n")
    cov = pd.DataFrame({"BUY": b.groupby("year").size(), "SELL/REDUCE": d[d.action.isin(["SELL", "REDUCE"])].groupby(d.rec_date.dt.year).size(),
                        "HOLD": d[d.action == "HOLD"].groupby(d.rec_date.dt.year).size(), "BUY with fool return": b[b.mf_return.notna()].groupby("year").size(),
                        "BUY with price": b[b.entry_date.notna()].groupby("year").size(), "BUY with 365d label": labelled.groupby("year").size()}).fillna(0).astype(int)
    add(md(cov.rename_axis("year")) + "\n")
    add("Source overlap (`source`): " + ", ".join(f"{k}={v}" for k, v in d.source.value_counts().items()) + ".\n")
    add("Action mix: SELL/HOLD/REDUCE only exist from 2014 (newrecs). 2002-2013 contain BUYs only, so exits are unobservable there except via `closed_date`.\n")

    add("## 5. Companies\n")
    add(f"Top repeated symbols: " + ", ".join(f"{k} ({v})" for k, v in b.symbol.value_counts().head(12).items()) + ".\n")
    add("Market cap at recommendation (only the xlsx era has it):\n")
    add(md(b.groupby("cap_bucket", observed=True).agg(n=("symbol", "size"), med_365d=("ret_365d", "median"), med_excess=("excess_365d", "median")).round(3)) + "\n")
    sec = b.groupby("sector").agg(n=("symbol", "size"), med_365d=("ret_365d", "median"), med_excess=("excess_365d", "median")).round(3).sort_values("n", ascending=False)
    add(f"Sector (current classification; {b.sector.isna().mean():.0%} unknown, mostly delisted names):\n")
    add(md(sec) + "\n")

    add("## 6. Returns per recommendation\n")
    h = pd.DataFrame({k: labelled[f"ret_{k}"].describe() for k in ["30d", "90d", "180d", "365d"]}).T
    add("Forward adj-close returns from entry (labelled BUYs; share beating SPY below):\n")
    h["beat_spy"] = [(labelled[f"excess_{k}"].dropna() > 0).mean() for k in ["30d", "90d", "180d", "365d"]]
    add(md(h.rename_axis("horizon")[["count", "mean", "std", "min", "25%", "50%", "75%", "max", "beat_spy"]].round(3)) + "\n")
    yr = labelled.groupby("year").agg(n=("symbol", "size"), med_365d=("ret_365d", "median"), med_excess=("excess_365d", "median"),
                                      beat_spy=("excess_365d", lambda s: (s > 0).mean())).round(3)
    add("By recommendation year (365d):\n"); add(md(yr) + "\n")
    team = labelled.groupby("team").agg(n=("symbol", "size"), med_365d=("ret_365d", "median"), med_excess=("excess_365d", "median"),
                                        beat_spy=("excess_365d", lambda s: (s > 0).mean())).round(3)
    add("By analyst (xlsx era, 2002-2020):\n"); add(md(team) + "\n")
    tr = b[b.mf_return.notna()]
    add(f"Fool's own returns (xlsx, as of 2020-04-08 or close date, n={len(tr)}): median {tr.mf_return.median():.1%}, mean {tr.mf_return.mean():.1%}, "
        f"median excess vs S&P {tr.mf_excess_return.median():+.1%}, {(tr.mf_excess_return > 0).mean():.0%} beat the S&P. "
        f"Top 10 picks = {tr.mf_return.nlargest(10).sum() / tr.mf_return.clip(lower=0).sum():.0%} of all positive return.\n")
    cols = ["rec_date", "symbol", "company", "mf_return", "ret_365d", "excess_365d"]
    add("Best Fool-reported picks:\n"); add(md(tr.nlargest(10, "mf_return")[cols], index=False) + "\n")
    add("Worst:\n"); add(md(tr.nsmallest(10, "mf_return")[cols], index=False) + "\n")
    rr = tr.dropna(subset=["risk_rating"])
    add(f"Fool risk rating (given only for David's picks, n={len(rr)}, range {rr.risk_rating.min():.0f}-{rr.risk_rating.max():.0f}): (risk_rating, mf_return) = {rr.risk_rating.corr(rr.mf_return):.2f}, i.e. the rating carries no outcome information.\n")

    add("## 7. Exits (SELL / REDUCE)\n")
    sr = sell_review(d, series)
    if len(sr):
        add(f"{len(sr)} sells matched to an earlier BUY with prices. Median hold {sr.held_days.median() / 365:.1f} years, "
            f"median return at sell {sr.hold_ret.median():.1%} (excess vs SPY {sr.hold_excess.median():+.1%}). "
            f"Post-sell 365d (n={sr.after_365d.notna().sum()}): median {sr.after_365d.median():+.1%}, median excess {sr.after_excess.median():+.1%}, "
            f"{(sr.after_excess.dropna() < 0).mean():.0%} of sold stocks went on to lag SPY (a good sell).\n")
    else:
        add("No sells could be matched to priced BUYs.\n")

    add("## 8. Why does Fool recommend these? What the data can and cannot say\n")
    add("**The dataset has no rationale text**: no thesis, no scores, no reason codes, only date, ticker, action and (for 2002-2020) returns. "
        "The proxies below are measured from prices at entry, so they are point-in-time.\n")
    f = b.dropna(subset=["mom_12m"])
    q = pd.DataFrame({"picks": f[["mom_12m", "rel_mom_12m", "from_52w_high", "from_52w_low"]].median(),
                      "share_positive": [(f.mom_12m > 0).mean(), (f.rel_mom_12m > 0).mean(), np.nan, np.nan]})
    add(f"Pre-recommendation profile (n={len(f)}, medians):\n"); add(md(pct(q["picks"]).to_frame("median_%").join(q["share_positive"].round(3))) + "\n")
    add(f"Picks were on average {f.rel_mom_12m.median():+.1%} vs SPY in the prior 12 months (median) and {-f.from_52w_high.median():.1%} below their 52-week high: "
        f"{'momentum-leaning, buying strength' if f.rel_mom_12m.median() > 0.05 else 'not an obvious momentum or dip-buying bias'}.\n")
    corr = f[["mom_12m", "rel_mom_12m", "from_52w_high", "from_52w_low", "ret_365d", "excess_365d"]].corr().loc[["mom_12m", "rel_mom_12m", "from_52w_high"], ["ret_365d", "excess_365d"]]
    add("Does pre-rec momentum predict the pick's own outcome? (correlations)\n"); add(md(corr.round(3)) + "\n")
    add("Stated philosophy (general knowledge, not in this data): Stock Advisor targets holding 5+ years, favouring durable-growth, founder-led, "
        "category-leading companies; David's picks skew to disruptive innovators and Tom's to quality compounders. The data is consistent with a "
        "growth tilt (tech, consumer, communication) but cannot confirm intent.\n")

    add("## 9. Data quality and limits\n")
    add("- Survivorship: price history is missing for acquired/bankrupt names unless filled from Tiingo; remaining gaps listed in the pipeline log.")
    add("- 2020-2025 picks lack Fool's own returns; labels there come from our price recomputation only.")
    add("- Market cap and risk rating only exist in the xlsx era; sector is today's classification.")
    add("- Fool returns vs ours: correlation 0.98 on overlapping picks but entry-price conventions differ; use `ret_*`/`excess_*` for labels.")
    add("- 365d overlapping windows: consecutive picks share market regimes, so observations are not independent; use time-based splits.")
    add("- Forward-return survivors in recent years are right-censored: 2025 picks have fewer labelled horizons.\n")

    add("## 10. Next steps for the ML dataset\n")
    add("1. Join point-in-time fundamentals (`financials` by `filed` date) for picks in the lake; extend lake coverage to the 368 picked names.")
    add("2. Features at rec date: momentum, drawdown, volatility, valuation, growth, margins, sector, cap bucket, analyst, repeat flag.")
    add("3. Targets: `excess_365d > 0` (classification) and `excess_365d` (regression); evaluate with walk-forward by recommendation year.")
    add("4. Add a control group: non-picked universe stocks with matching dates, otherwise a model only learns 'what a stock looks like' rather than 'what Fool chooses'.")
    add("5. Text rationale: fool.com articles per pick (paywalled) would be the only way to model the 'why'.\n")
    return "\n".join(L)


def main() -> None:
    OUT.write_text(build())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
